# Generated by Django 3.2.6 on 2021-10-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateringForm',
            fields=[
                ('catering_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('package_type', models.CharField(blank=True, choices=[('The Lieutant', 'The Lieutant'), ('The Captain', 'The Captain'), ('The Sargeant', 'The Sargeant')], max_length=25)),
                ('people_attending', models.CharField(max_length=25)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additional_hours', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=0, max_length=25)),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('message', models.TextField(blank=True, max_length=1500, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('VENMO', 'Venmo'), ('CASH', 'Cash'), ('CARD', 'Card')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('contact_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('contact_type', models.CharField(blank=True, choices=[('QUESTION', 'Question'), ('FEEDBACK', 'Feedback'), ('CONCERN', 'Concern')], max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('message', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewForm',
            fields=[
                ('review_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_initial', models.CharField(max_length=25)),
                ('date_visited', models.DateField()),
                ('food_rating', models.CharField(blank=True, choices=[('Not very good', 'Not very good'), ('Not good', 'Not good'), ('OK', 'OK'), ('Good', 'Good'), ('Very good', 'Very good')], max_length=25)),
                ('service_rating', models.CharField(blank=True, choices=[('Not very good', 'Not very good'), ('Not good', 'Not good'), ('OK', 'OK'), ('Good', 'Good'), ('Very good', 'Very good')], max_length=25)),
                ('review_message', models.TextField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
            ],
        ),
    ]
