# Generated by Django 3.2.6 on 2021-11-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='image',
        ),
    ]
