# Generated by Django 3.2.6 on 2021-11-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_remove_contactform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringform',
            name='package_type',
            field=models.CharField(blank=True, choices=[('The Lieutant', 'The Lieutenant'), ('The Captain', 'The Captain'), ('The Sargeant', 'The Sargeant')], max_length=25),
        ),
    ]
