# Generated by Django 3.2.6 on 2021-09-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0004_auto_20210908_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
